version: 2.1

######################
#     Structure      #
######################
# Aliases
# Commands
# Executors
# Jobs
# Workflow(s)

######################
#      Aliases       #
######################
aliases:
- &GCP-auth
  name: GCP Authenticate
  command: |
    echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
    tools/gcp_authenticate.sh
- &docker-login
  name: Docker login
  command: |
    docker login -u "_json_key" -p "${DOCKER_PASSWORD}" eu.gcr.io
- &docker-build-and-push
  name: Docker build and push
  command: |
    IMAGE="eu.gcr.io/entur-system-1287/protoc-gen-push-doc"
    echo "Image: ${IMAGE}"
    docker build -t $IMAGE .
    docker push $IMAGE

######################
#       Jobs         #
######################

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: tools/gcloud_install.sh
      - run: *GCP-auth
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *docker-login
      - run: *docker-build-and-push

######################
#     Workflows      #
######################

workflows:
  version: 2.1
  build-protoc-gen-push-doc-image:
    jobs:
      - build:
          context: global
